# Generated by Django 6.0.3 on 2026-03-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='fees_per_term',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
