# Generated by Django 6.0.3 on 2026-03-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='college_images/'),
        ),
    ]
