# Generated by Django 6.0.3 on 2026-03-21 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_alter_college_image'),
        ('university', '0002_university_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colleges', to='university.university'),
        ),
    ]
